# Generated by Django 5.1.1 on 2024-09-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='nome',
        ),
    ]
