# Generated by Django 5.1.1 on 2024-09-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_rename_category_category_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
    ]
