# Generated by Django 5.1.1 on 2024-09-08 21:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_rename_category_category_nome'),
        ('cozinha', '0002_alter_kitchen_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kitchen',
            new_name='Food',
        ),
    ]
